### ISSUE TITLE
Farming: Table Pagination

### ISSUE THREAD

**Issue by strd381** [GooseFX1/gfx-web-app#101]
Would be great that the table on Farming has pagination feature.
![screenshot](https://user-images.githubusercontent.com/86629632/151066940-7144b6cb-2f93-4354-909a-001a6be1c062.png)

**Comment by usgoose** [comment]
Yes I agree. @bdcorps can take a look

**Comment by strd381** [comment]
Thanks @bdcorps it looks great. There is still an issue with light mode. Please check the attached screenshot
![screenshot](https://user-images.githubusercontent.com/86629632/151599861-c74aff0f-7a2b-48ad-b3dc-38d7d262c5b8.png)
.

**Comment by bdcorps** [comment]
Should be fixed here - https://github.com/GooseFX1/gfx-web-app/pull/112
