### ISSUE TITLE
Enhance Display Grid Synths

### ISSUE THREAD

**Issue by usgoose** [GooseFX1/gfx-web-app#30]
- [ ] Add decimal places for higher priced assets
- [ ] Number of digits on left of decimal for asset price = Number of decimals needed to display for amount and delta (4 decimal places)
- [ ] Build logic around display decimals with higher prices

**Comment by antimatterrr** [comment]
After discussions and examining other synthetic projects, we elected to go with 4 decimal places for an easy fix. We will have to potentially enhance the higher priced assets in future (btc, etc, ...)
