### ISSUE TITLE
Tool tip for the delta column - Synths

### ISSUE THREAD

**Issue by usgoose** [GooseFX1/gfx-web-app#31]
- [ ] Tooltip for representation of the delta values (@stunt101harm @antimatterrr please provide text for the tooltip)

**Comment by antimatterrr** [comment]
Before tool tip text can be finalized, we must decide what value we want the delta to represent. (%, $, etc. )

**Comment by majeedus** [comment]
@stunt101harm if you have wifi on the flight then fill in the text for the tooltip so @0xWWW please

**Comment by stunt101harm** [comment]
If the position delta is positive that means that you will make money for every dollar the asset increases. For example if the position delta is 0.5 then you will make 0.5 dollars for every dollar increase. Conversely you will lose 0.5 dollars for every dollar the asset decreases in price. 

Likewise if the position delta is negative then that means you will make money as the price moves down. For example if the position delta is -0.5 then you make make 0.5 dollars for every dollar the price of the asset decreases. Conversely if the price of the asset moves up you will lose 0.5 dollars for every dollar that the asset increases in price

**Comment by 0xWWW** [comment]
@stunt101harm - could you send me the screenshot of tooltip?

**Comment by stunt101harm** [comment]
Screenshot of the text for tooltip or a screenshot with location of where tooltip will be?

**Comment by 0xWWW** [comment]
both of them, please
