### ISSUE TITLE
Mobile Responsiveness - Web App

### ISSUE THREAD

**Issue by majeedus** [GooseFX1/gfx-web-app#33]
Web app has to be more mobile friendly (www.app.goosefx.io)

See screenshots below for issues on iPhone 11 Pro:

![signal-2021-11-29-111019_002](https://user-images.githubusercontent.com/6387294/143902682-cb80b415-dfb0-421b-a872-7785f8b02c5f.jpeg)
![signal-2021-11-29-111019_001](https://user-images.githubusercontent.com/6387294/143902686-bb7ed8a2-876a-45e7-bd88-c0b477751196.jpeg)

Make sure any changes don't break the web, desktop, iPad responsiveness.

**Comment by usgoose** [comment]
Footer is missing here still ![image](https://user-images.githubusercontent.com/6387294/147587887-a33bf7cd-bea5-4091-87f5-dd9094699792.jpeg)

**Comment by walt-1** [comment]
This issue has been solved in the [gfx-homepage PR#36](https://github.com/GooseFX1/gfx-homepage/pull/36) which is currently still in staging environment with the rest of the v2 homepage updates.
