### ISSUE TITLE
Link to Docs on About Us

### ISSUE THREAD

**Issue by usgoose** [GooseFX1/gfx-web-app#64]
When you click on About, it should create a dropdown menu that has an item called, "Docs" and leads to https//docs.goosefx.io

![image](https://user-images.githubusercontent.com/6387294/147587984-11da20a8-1a46-4584-8ebf-92a5b7e3558b.png)

**Comment by walt-1** [comment]
recreated this as [issue in gfx-homepage](https://github.com/GooseFX1/gfx-homepage/issues/37)
