### ISSUE TITLE
NFT Market: Footer Carousel has wrong dimensions

### ISSUE THREAD

**Issue by walt-1** [GooseFX1/gfx-web-app#74]
The footer carousel on the NFT page needs proper dimensions to account for its parents width while keeping the controls visible. 

Currently, its width exceeds the boundaries of the page and the controls to scroll left and right are pushed outside the bounds of the page making them not visible or clickable.

Implement styles so that the carousel fits within the boundaries of its container so the controls are visible and clickable.

**Comment by strd381** [comment]
@lukewalt review the PR(#87 ). Not sure if that's what you wanted to fix.
